###
POST http://localhost:3000/api/calarea
Content-Type: application/json

{
    "geometry": {"type": "Polygon","coordinates": [[ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0] ]]},
    "srid": 32647
}

###
POST http://localhost:3000/api/split
Content-Type: application/json

{
  "polygon": {"type": "Polygon", "coordinates": [[[98.94974063401833,18.80288760560407],[98.94974063401833,18.80274987614453],[98.95043452837308,18.80274987614453],[98.95043452837308,18.80288760560407],[98.94974063401833,18.80288760560407]]]},
  "line": {"type": "LineString", "coordinates": [[98.94995215272888,18.802934088357546],[98.94995954337315,18.802703212750473]]}, 
  "srid": 32647
}

###
GET http://localhost:3400/rub/api/users


###
POST http://localhost:3400/rub/api/layerlist
Content-Type: application/json

{
  "tb_name":     "nan",
  "tb_fullname": "tb_rub_nan",
  "remark":      "something"
}

###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS:V_PARCEL48&query_layers=LANDSMAPS:V_PARCEL48&bbox=103.29620361328124,14.691467285156245,103.29757690429686,14.69284057617188&width=256&height=256&srs=EPSG:4326&x=128&y=128&info_format=application/vnd.ogc.gml


###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/ows?service=WFS&version=2.0.0&request=GetFeature&typeName=LANDSMAPS:V_PARCEL48&outputFormat=GML3&srsName=EPSG:4326&bbox=103.29620361328124,14.691467285156245,103.29757690429686,14.69284057617188,EPSG:4326

###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?transparent=true&format=image%2Fpng&viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetMap&styles=&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29208374023436%2C14.694900512695314%2C103.2927703857422%2C14.695587158203125&width=256&height=256&srs=EPSG%3A4326&info_format=application/vnd.ogc.gml

###
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms/reflect?layers=LANDSMAPS:V_PARCEL48&format=rss&viewparams=utmmap:563821624

### get gml
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?format=rss&viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetMap&styles=&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29345703124999%2C14.694213867187504%2C103.29895019531247%2C14.699707031249995&width=256&height=256&srs=EPSG%3A4326

### get json
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29372122%2C14.69413140%2C103.29372123%2C14.69413141&width=256&height=256&srs=EPSG%3A4326&query_layers=LANDSMAPS%3AV_PARCEL48&info_format=application%2Fjson&x=103&y=85

### get json
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?viewparams=utmmap:563821624&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS:V_PARCEL48&bbox=103.29372123,14.69413141,103.293721230.01,14.694131410.01&width=256&height=256&srs=EPSG:4326&query_layers=LANDSMAPS:V_PARCEL48&info_format=application/json&x=103&y=85


###
GET https://landsmaps.dol.go.th/Service/ProvinceService/configapi.json

### get pro ldd
GET https://landsmaps.dol.go.th/apiService/Master/GetProvince HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiYjMyMThiMGQtNzUzZi00NWNkLTljNWEtYTMxYWRkMzk5MTNlIiwiaWF0IjoiMDYvMDUvMjAyNSAwNDoyNjoyNSIsIm5iZiI6MTc0OTA5NzU4NSwiZXhwIjoxNzQ5MTgzOTg1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.lLcXCyblEJo23iEPaladKbidMJdex_aNHgrjI_m7gaDx6RrGA-HhYjMIxDISO5hXKq7dUFk810v4vGJ7lzRPGg
Accept: application/json

### get amp ldd
GET https://landsmaps.dol.go.th/apiService/Master/GetAmphoe/41 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiYjMyMThiMGQtNzUzZi00NWNkLTljNWEtYTMxYWRkMzk5MTNlIiwiaWF0IjoiMDYvMDUvMjAyNSAwNDoyNjoyNSIsIm5iZiI6MTc0OTA5NzU4NSwiZXhwIjoxNzQ5MTgzOTg1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.lLcXCyblEJo23iEPaladKbidMJdex_aNHgrjI_m7gaDx6RrGA-HhYjMIxDISO5hXKq7dUFk810v4vGJ7lzRPGg
Accept: application/json

### 
GET https://landsmaps.dol.go.th/apiService/LandsMaps/GetParcelByParcelNo/32/05/30980 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiYjMyMThiMGQtNzUzZi00NWNkLTljNWEtYTMxYWRkMzk5MTNlIiwiaWF0IjoiMDYvMDUvMjAyNSAwNDoyNjoyNSIsIm5iZiI6MTc0OTA5NzU4NSwiZXhwIjoxNzQ5MTgzOTg1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.lLcXCyblEJo23iEPaladKbidMJdex_aNHgrjI_m7gaDx6RrGA-HhYjMIxDISO5hXKq7dUFk810v4vGJ7lzRPGg
Accept: application/json

###
GET http://localhost:3400/rub/api/ldd_getpacelbypacelnumber/32/05/30980

###
GET https://landsmaps.dol.go.th/apiService/LandsMaps/GetParcelByLatLon/14.69413141/103.29372123
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyZWdpc3Rlcl90eXBlX3NlcSI6IjgiLCJ1c2VyX2dyb3VwX2RhdGFfbGlzdCI6IjEsMSwwLDAsMCwwLDAsMSIsInBlcnNvbmFsX2lkIjoiIiwianRpIjoiYjMyMThiMGQtNzUzZi00NWNkLTljNWEtYTMxYWRkMzk5MTNlIiwiaWF0IjoiMDYvMDUvMjAyNSAwNDoyNjoyNSIsIm5iZiI6MTc0OTA5NzU4NSwiZXhwIjoxNzQ5MTgzOTg1LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDozMDAwMS8iLCJhdWQiOiJMYW5kc01hcHMifQ.lLcXCyblEJo23iEPaladKbidMJdex_aNHgrjI_m7gaDx6RrGA-HhYjMIxDISO5hXKq7dUFk810v4vGJ7lzRPGg
Accept: application/json


### get json
GET https://landsmaps.dol.go.th/geoserver/LANDSMAPS/wms?viewparams=utmmap%3A563821624&=&service=WMS&version=1.1.1&request=GetFeatureInfo&layers=LANDSMAPS%3AV_PARCEL48&bbox=103.29372122%2C14.69413140%2C103.29372123%2C14.69413141&width=256&height=256&srs=EPSG%3A4326&query_layers=LANDSMAPS%3AV_PARCEL48&info_format=application%2Fjson&x=103&y=85
