/**
 * convert_shpck.js
 * Reads all .shp files from ../shpck/ ("แปลงตัวอย่าง" — sample/spot-check plots
 * used to verify เกษตรกร's registered plots) and produces one file:
 *
 *   ../postgis/shpck.sql — PostgreSQL SQL file with DDL + INSERT data
 *                          run with: psql -U postgres -d rub2 -f shpck.sql
 *
 * The shapefiles are in UTM (zone 47N or 48N, read from each .prj), not
 * lon/lat — so unlike convert_shpall.js, every row is reprojected to
 * EPSG:4326 with PostGIS's ST_Transform at import time (no proj4 needed in
 * Node; EPSG:326xx is built into PostGIS's spatial_ref_sys).
 *
 * Run from the nodejs/ directory:
 *   node convert_shpck.js
 */

require('dotenv').config();
const shapefile = require('shapefile');
const fs        = require('fs');
const path      = require('path');

const DB_NAME = process.env.DB_NAME || 'rub2';
const DB_USER = process.env.DB_USER || 'postgres';

const SHPCK_DIR = path.join(__dirname, '..', 'shpck');
const SQL_OUT   = path.join(__dirname, '..', 'postgis', 'shpck.sql');

// ── helpers ──────────────────────────────────────────────────────────────────

function sqlEsc(val) {
    if (val === null || val === undefined) return 'NULL';
    return "'" + String(val).replace(/'/g, "''") + "'";
}

// อ่านโซน UTM จาก .prj ของแต่ละไฟล์ (ห้าม hardcode — ไฟล์ชุดนี้คาบเกี่ยวทั้งโซน 47N และ 48N)
function utmSridFromPrj(prjPath) {
    const wkt = fs.readFileSync(prjPath, 'utf8');
    const m = wkt.match(/UTM_Zone_(\d+)([NS])/i);
    if (!m) throw new Error(`อ่านโซน UTM จาก ${prjPath} ไม่ได้: ${wkt}`);
    const zone = parseInt(m[1], 10);
    const hemisphere = m[2].toUpperCase();
    return (hemisphere === 'N' ? 32600 : 32700) + zone;
}

// field ชื่อ code มาไม่ตรงกันระหว่างไฟล์ (code / Code / Code_1) — รวมเป็นชื่อเดียว
function readCode(props) {
    return props.code || props.Code || props.Code_1 || props.CODE || null;
}

function regionFromFileName(shpFile) {
    // "Polygon_แปลงตัวอย่าง_CE_47.shp" -> "CE_47"
    return shpFile.replace(/^Polygon_แปลงตัวอย่าง_/, '').replace(/\.shp$/i, '');
}

function featureToSqlValues(f, id, srid, region) {
    const code = readCode(f.properties || {});
    const geomJson = JSON.stringify({ type: f.geometry.type, coordinates: f.geometry.coordinates })
                         .replace(/'/g, "''");
    return `(${[
        id,
        sqlEsc(code),
        sqlEsc(region),
        `ST_Multi(ST_Transform(ST_SetSRID(ST_GeomFromGeoJSON('${geomJson}'::text), ${srid}), 4326))`
    ].join(',')})`;
}

// ── SQL DDL header ────────────────────────────────────────────────────────────

const SQL_HEADER = `\\c ${DB_NAME}
-- Auto-generated by convert_shpck.js
-- แปลงตัวอย่าง (sample/spot-check plots) จาก shpck/ — เก็บไว้ตรวจสอบแปลงจริง

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', 'public', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Drop and recreate table with latest data
DROP TABLE IF EXISTS public.shpck CASCADE;

CREATE TABLE public.shpck (
    id integer NOT NULL,
    code text,
    src_region text,
    geom public.geometry(MultiPolygon,4326)
);

ALTER TABLE public.shpck OWNER TO ${DB_USER};

CREATE SEQUENCE public.shpck_id_seq
    AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

ALTER SEQUENCE public.shpck_id_seq OWNER TO ${DB_USER};
ALTER SEQUENCE public.shpck_id_seq OWNED BY public.shpck.id;
ALTER TABLE ONLY public.shpck ALTER COLUMN id SET DEFAULT nextval('public.shpck_id_seq'::regclass);

-- Spatial index for fast bbox queries
CREATE INDEX shpck_geom_idx ON public.shpck USING GIST (geom);

-- ─── Data ────────────────────────────────────────────────────────────────────

`;

const INSERT_COLS = `INSERT INTO public.shpck (id,code,src_region,geom) VALUES\n`;

// ── main ──────────────────────────────────────────────────────────────────────

async function main() {
    const shpFiles = fs.readdirSync(SHPCK_DIR)
        .filter(f => f.toLowerCase().endsWith('.shp')).sort();

    const sqlStream = fs.createWriteStream(SQL_OUT, { encoding: 'utf8' });
    sqlStream.write(SQL_HEADER);

    let totalFeatures = 0;
    let rows = [];

    for (const shpFile of shpFiles) {
        const shpPath = path.join(SHPCK_DIR, shpFile);
        const dbfPath = shpPath.replace(/\.shp$/i, '.dbf');
        const prjPath = shpPath.replace(/\.shp$/i, '.prj');
        const srid = utmSridFromPrj(prjPath);
        const region = regionFromFileName(shpFile);
        console.log(`อ่าน: ${shpFile} (SRID ${srid}, ภาค ${region})`);
        let fileCount = 0;

        const source = await shapefile.open(shpPath, dbfPath, { encoding: 'UTF-8' });
        let result;
        while (!(result = await source.read()).done) {
            const f = result.value;
            if (!f || !f.geometry) continue;

            totalFeatures++;
            fileCount++;
            rows.push(featureToSqlValues(f, totalFeatures, srid, region));
        }
        console.log(`  → ${fileCount} แปลง`);
    }

    sqlStream.write('BEGIN;\n' + INSERT_COLS + rows.join(',\n') + ';\nCOMMIT;\n\n');
    sqlStream.write(`SELECT setval('public.shpck_id_seq', ${totalFeatures}, true);\n`);
    await new Promise(r => { sqlStream.end(); sqlStream.on('finish', r); });

    console.log(`\nบันทึกสำเร็จ: ${SQL_OUT}`);
    console.log(`รวมทั้งหมด: ${totalFeatures} แปลง`);
    console.log(`\nวิธีนำเข้าฐานข้อมูล:`);
    console.log(`  psql -U ${DB_USER} -d ${DB_NAME} -f "${SQL_OUT}"`);
}

main().catch(err => {
    console.error('เกิดข้อผิดพลาด:', err);
    process.exit(1);
});
